ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  domain: "http://localhost:8080/"
  audience: "client"
  issuer: "http://localhost:8080/"
  realm: "ktor-messaging-api"
  claimField: "id"
  secret: ${JWT_SECRET}
database:
  url: "jdbc:mysql://localhost:3307/messaging_db"
  user: "user"
  password: ${DB_PASSWORD}
  driver: "com.mysql.cj.jdbc.Driver"
